# 京阪七天七夜 旅遊資料模組

DAYS = [
    {
        "day": 0,
        "date": "2026/06/20（六）",
        "theme": "啟程",
        "subtitle": "飛越海峽，踏入古都",
        "city": "台灣 → 關西 → 京都",
        "color": "#7B9EA6",
        "hotel": "維瑟爾坎帕納京都五條飯店",
        "mood": "從熟悉的島嶼起飛，在機艙窗邊目送台灣輪廓消失於雲層之後，某種「真的要出發了」的感覺才真正落地。三個小時後，關西的海岸線從地平線升起，帶著與台灣截然不同的輪廓。",
        "stops": [
            {
                "time": "12:15", "end": "15:15",
                "name": "臺灣桃園國際機場",
                "type": "出發",
                "icon": "✈️",
                "coord": (25.0777, 121.2328),
                "desc": "辦理登機手續、托運行李，完成出境後至候機室候機。",
                "tips": "免稅區可選購零食帶上機；建議使用機場飲水機補水。",
                "green": "自備水瓶，使用機場飲水機，避免購買一次性瓶裝水。",
                "transport_next": None,
            },
            {
                "time": "15:15", "end": "19:00",
                "name": "飛行中 TPE → KIX",
                "type": "交通",
                "icon": "🛫",
                "coord": (30.0, 128.0),
                "desc": "飛行時間約 2 小時 45 分，日本時間比台灣快 1 小時。",
                "tips": "機上可用餐；在機上完成 Visit Japan Web 填寫。",
                "green": None,
                "transport_next": None,
            },
            {
                "time": "19:00", "end": "21:00",
                "name": "關西國際機場",
                "type": "抵達",
                "icon": "🛬",
                "coord": (34.4320, 135.2304),
                "desc": "辦理入境審查、領取行李，購買 ICOCA 交通卡與 HARUKA 票券。",
                "tips": "機場便利商店可買輕食補充能量。",
                "green": "搭乘鐵路前往市區，避免包車，減少碳排。",
                "transport_next": {
                    "mode": "JR HARUKA 特急 + 地下鐵烏丸線",
                    "walking": False,
                    "duration": "約 98 分鐘",
                    "detail": "KIX → 京都站（HARUKA 約 75 分）→ 烏丸線 K11→K10（約 2 分）→ 步行 5 分",
                    "origin": (34.4320, 135.2304),
                    "dest": (34.9963, 135.7606),
                    "travelmode": "transit",
                },
            },
            {
                "time": "22:38", "end": "23:59",
                "name": "維瑟爾坎帕納京都五條飯店",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.9963, 135.7606),
                "desc": "辦理入住，整理行李，確認明日宇治行程路線。",
                "tips": "周邊便利商店可購買宵夜；備妥明日水瓶與雨具。",
                "green": None,
                "transport_next": None,
            },
        ],
    },
    {
        "day": 1,
        "date": "2026/06/21（日）",
        "theme": "茶韻鳥居",
        "subtitle": "宇治茶鄉與千本鳥居",
        "city": "宇治 × 伏見 × 京都",
        "color": "#7A9E7E",
        "hotel": "維瑟爾坎帕納京都五條飯店",
        "mood": "宇治的早晨很安靜。茶田的綠意從坡地一路延伸至橋邊，宇治川的水聲比想像中清澈。那種緩慢，不是因為沒有地方要去，而是因為這裡的一切都在提醒你：不必那麼快。",
        "stops": [
            {
                "time": "08:00", "end": "09:00",
                "name": "維瑟爾坎帕納京都五條飯店",
                "type": "早餐",
                "icon": "🍵",
                "coord": (34.9963, 135.7606),
                "desc": "在飯店或周邊享用早餐，準備水瓶與雨具。",
                "tips": "可選飯店早餐或周邊在地咖啡店。",
                "green": None,
                "transport_next": {
                    "mode": "京阪電車",
                    "walking": False,
                    "duration": "約 38 分鐘",
                    "detail": "五條站（京阪）→ 中書島轉乘京阪宇治線 → 宇治站，步行 5 分至平等院",
                    "origin": (34.9963, 135.7606),
                    "dest": (34.8893, 135.8074),
                    "travelmode": "transit",
                },
            },
            {
                "time": "09:38", "end": "11:38",
                "name": "平等院",
                "type": "古蹟文化",
                "icon": "🏛️",
                "coord": (34.8893, 135.8074),
                "desc": "參觀世界遺產平等院鳳凰堂，欣賞池泉庭園與平安時代建築之美。",
                "tips": "鳳凰堂倒映於水面，建議早上光線較柔和時拍攝。",
                "green": "提早參訪，降低旺季人潮對環境的衝擊。",
                "mood": "鳳凰堂的倒影浮在水面上，像是過去一千年都在等待有人靜靜凝視。池水沒有澄澈到失去真實感，剛好留著一點搖曳——那才是活的。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 10 分鐘",
                    "detail": "沿宇治橋通步行",
                    "origin": (34.8893, 135.8074),
                    "dest": (34.8910, 135.8068),
                    "travelmode": "walking",
                },
            },
            {
                "time": "11:48", "end": "13:18",
                "name": "中村藤吉本店 宇治本店",
                "type": "餐飲",
                "icon": "🍵",
                "coord": (34.8910, 135.8068),
                "desc": "百年老舖享用宇治茶甜點與茶料理。推薦生茶凍、抹茶蕨餅、茶蕎麥麵。",
                "tips": "用餐可能需排隊 20–40 分鐘，可先取號再附近散步等候。",
                "green": None,
                "mood": "進店之前要先排隊。等待本身不算浪費時間——宇治人用幾百年把一片茶葉養到這個滋味，你多等二十分鐘算什麼。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 1 分鐘",
                    "detail": "宇治橋通步行即達",
                    "origin": (34.8910, 135.8068),
                    "dest": (34.8918, 135.8060),
                    "travelmode": "walking",
                },
            },
            {
                "time": "13:19", "end": "14:19",
                "name": "宇治橋通商店街振興組合",
                "type": "散步購物",
                "icon": "🛍️",
                "coord": (34.8918, 135.8060),
                "desc": "逛宇治在地商店街，採購茶葉、和菓子、陶器等地方特產。",
                "tips": "選擇有地方故事的茶葉與茶具作紀念品，避免大量一次性包裝伴手禮。",
                "green": "選擇在地小店，支持宇治地方商業。",
                "transport_next": {
                    "mode": "京阪電車",
                    "walking": False,
                    "duration": "約 31 分鐘",
                    "detail": "宇治站（京阪）→ 中書島轉乘京阪本線 → 伏見稻荷站，步行 5 分",
                    "origin": (34.8918, 135.8060),
                    "dest": (34.9671, 135.7727),
                    "travelmode": "transit",
                },
            },
            {
                "time": "14:50", "end": "16:50",
                "name": "伏見稻荷大社",
                "type": "古蹟文化",
                "icon": "⛩️",
                "coord": (34.9671, 135.7727),
                "desc": "參拜千本鳥居，可選擇登山或僅在山腳周邊欣賞。",
                "tips": "登山段較陡，量力而為；境內保持安靜，避免觸碰鳥居柱。",
                "green": "避免尖峰時段，減少對神社環境的衝擊。",
                "mood": "鳥居一根接著一根，紅得有點不真實。光從縫隙透進來，切成一段段。走在裡面不像觀光，比較像是穿越別人的祈禱。",
                "transport_next": {
                    "mode": "京阪電車",
                    "walking": False,
                    "duration": "約 23 分鐘",
                    "detail": "伏見稻荷站（京阪）→ 三条站，步行至高木批發超市",
                    "origin": (34.9671, 135.7727),
                    "dest": (35.0090, 135.7730),
                    "travelmode": "transit",
                },
            },
            {
                "time": "17:13", "end": "19:13",
                "name": "高木批發超市三条店",
                "type": "散步購物",
                "icon": "🛒",
                "coord": (35.0090, 135.7730),
                "desc": "批發型超市採購零食、飲料、調味料，是採購伴手禮的好去處。",
                "tips": "部分商品比一般超市便宜；確認是否限制一般消費者入場。",
                "green": None,
                "transport_next": {
                    "mode": "京阪電車",
                    "walking": False,
                    "duration": "約 19 分鐘",
                    "detail": "三条站（京阪）→ 五条站，步行 5 分至飯店",
                    "origin": (35.0090, 135.7730),
                    "dest": (34.9963, 135.7606),
                    "travelmode": "transit",
                },
            },
            {
                "time": "19:32", "end": "19:42",
                "name": "維瑟爾坎帕納京都五條飯店",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.9963, 135.7606),
                "desc": "短暫放置物品，補充飲水，準備前往京都車站晚餐。",
                "tips": None,
                "green": None,
                "transport_next": {
                    "mode": "地下鐵烏丸線",
                    "walking": False,
                    "duration": "約 13 分鐘",
                    "detail": "K10（五条）→ K11（京都）約 2 分，步行至車站周邊",
                    "origin": (34.9963, 135.7606),
                    "dest": (34.9858, 135.7588),
                    "travelmode": "transit",
                },
            },
            {
                "time": "19:55", "end": "22:55",
                "name": "京都車站周邊",
                "type": "晚餐",
                "icon": "🍜",
                "coord": (34.9858, 135.7588),
                "desc": "在京都車站周邊享用晚餐，推薦第 10 樓拉麵小路、地下街 The CUBE 或伊勢丹美食街。",
                "tips": "旺季建議 19:30 前入座；可順道購買明日早餐。",
                "green": None,
                "transport_next": {
                    "mode": "地下鐵烏丸線",
                    "walking": False,
                    "duration": "約 13 分鐘",
                    "detail": "K11（京都）→ K10（五条），步行 5 分至飯店",
                    "origin": (34.9858, 135.7588),
                    "dest": (34.9963, 135.7606),
                    "travelmode": "transit",
                },
            },
            {
                "time": "23:08", "end": "23:59",
                "name": "維瑟爾坎帕納京都五條飯店",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.9963, 135.7606),
                "desc": "返回飯店盥洗休息，確認明日東山行程。",
                "tips": "明日行程從下鴨神社開始，建議 8 點前出發。",
                "green": None,
                "transport_next": None,
            },
        ],
    },
    {
        "day": 2,
        "date": "2026/06/22（一）",
        "theme": "東山古道",
        "subtitle": "石板坡道與河原町之夜",
        "city": "下鴨 × 東山 × 祇園 × 河原町",
        "color": "#B5977A",
        "hotel": "維瑟爾坎帕納京都五條飯店",
        "mood": "東山的石板路有一種讓人放慢腳步的魔力。不是因為路難走，而是因為你會忍不住想停下來——看某一棟竹格子的門扉，或是一段被青苔爬滿的石牆角。那些停頓，才是旅行真正發生的時刻。",
        "stops": [
            {
                "time": "08:00", "end": "09:00",
                "name": "維瑟爾坎帕納京都五條飯店",
                "type": "早餐",
                "icon": "☕",
                "coord": (34.9963, 135.7606),
                "desc": "享用早餐，確認下鴨神社交通路線。今日步行量大，建議穿著舒適鞋子。",
                "tips": None,
                "green": None,
                "transport_next": {
                    "mode": "京都市公車",
                    "walking": False,
                    "duration": "約 36 分鐘",
                    "detail": "Karasuma Gojo 公車站搭 205 系統往北至「下鴨神社前」下車",
                    "origin": (34.9963, 135.7606),
                    "dest": (35.0388, 135.7727),
                    "travelmode": "transit",
                },
            },
            {
                "time": "09:36", "end": "10:36",
                "name": "賀茂御祖神社（下鴨神社）",
                "type": "古蹟文化",
                "icon": "🌳",
                "coord": (35.0388, 135.7727),
                "desc": "世界遺產下鴨神社，漫步糺之森原始林道，感受京都最古老的綠意。",
                "tips": "神社境內茶屋「さるや」供應葵餅與抹茶，可小憩。",
                "green": None,
                "mood": "糺之森的樹都很老，老到連樹根都長成小山丘。走在這裡不像走在神社，比較像走進某個比任何人都更早存在的事物裡面。",
                "transport_next": {
                    "mode": "京都市公車",
                    "walking": False,
                    "duration": "約 51 分鐘",
                    "detail": "「下鴨神社前」搭公車至「五条坂」下車，步行上坡約 10 分鐘至清水寺",
                    "origin": (35.0388, 135.7727),
                    "dest": (34.9948, 135.7850),
                    "travelmode": "transit",
                },
            },
            {
                "time": "11:27", "end": "12:27",
                "name": "清水寺",
                "type": "古蹟文化",
                "icon": "⛩️",
                "coord": (34.9948, 135.7850),
                "desc": "參拜清水寺本堂，站上清水舞台俯瞰京都市景，品飲音羽瀑布。",
                "tips": "清水舞台的木柱不用一根釘子，純靠榫卯結構，建議仔細觀察工法。",
                "green": "提早參訪，減少旺季人流對山寺環境的壓力。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 7 分鐘",
                    "detail": "清水寺出口步行下坡",
                    "origin": (34.9948, 135.7850),
                    "dest": (34.9961, 135.7820),
                    "travelmode": "walking",
                },
            },
            {
                "time": "12:34", "end": "13:04",
                "name": "産寧坂（三年坂）",
                "type": "散步購物",
                "icon": "🏮",
                "coord": (34.9961, 135.7820),
                "desc": "漫步石板坡道，逛陶器、和紙、風呂敷等地方工藝小店。",
                "tips": "石板路濕滑，下雨天特別小心；選擇耐用的在地工藝品作紀念。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 6 分鐘",
                    "detail": "步行至下一段坡道",
                    "origin": (34.9961, 135.7820),
                    "dest": (34.9975, 135.7810),
                    "travelmode": "walking",
                },
            },
            {
                "time": "13:10", "end": "13:40",
                "name": "二寧坂（二年坂）",
                "type": "散步購物",
                "icon": "🏮",
                "coord": (34.9975, 135.7810),
                "desc": "保存完好的町家建築，逛和菓子、竹工藝等小店。",
                "tips": "傳說踩到坡道磚縫會帶來厄運，謹慎步行。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "步行即達",
                    "origin": (34.9975, 135.7810),
                    "dest": (34.9980, 135.7800),
                    "travelmode": "walking",
                },
            },
            {
                "time": "13:42", "end": "14:12",
                "name": "一年坂（一念坂）",
                "type": "散步購物",
                "icon": "🪴",
                "coord": (34.9980, 135.7800),
                "desc": "最安靜的石板小道，青苔石牆與竹林圍繞，適合放慢腳步拍照。",
                "tips": "人潮最少的坡道，可安靜停留觀察。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 5 分鐘",
                    "detail": "步行至石塀小路",
                    "origin": (34.9980, 135.7800),
                    "dest": (35.0010, 135.7790),
                    "travelmode": "walking",
                },
            },
            {
                "time": "14:15", "end": "14:45",
                "name": "石塀小路",
                "type": "古蹟文化",
                "icon": "🪨",
                "coord": (35.0010, 135.7790),
                "desc": "漫步石塀小路窄巷，感受京都最具氛圍的料亭與傳統旅館街道。",
                "tips": "非公共道路，請勿大聲喧嘩，尊重周邊住戶隱私。",
                "green": None,
                "mood": "石塀小路窄到兩個人並肩走會有點侷促。那種侷促不讓人不舒服，反而讓人不由得輕聲說話——彷彿這條巷子本來就不是設計來熱鬧的。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 7 分鐘",
                    "detail": "步行至八坂神社",
                    "origin": (35.0010, 135.7790),
                    "dest": (35.0036, 135.7785),
                    "travelmode": "walking",
                },
            },
            {
                "time": "14:52", "end": "15:52",
                "name": "京都八坂神社",
                "type": "古蹟文化",
                "icon": "⛩️",
                "coord": (35.0036, 135.7785),
                "desc": "參拜八坂神社，感受祇園地區的信仰氛圍與朱紅大門。",
                "tips": "境內保持安靜；6 月下旬祇園祭準備期間有特別氛圍。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 8 分鐘",
                    "detail": "步行至花見小路",
                    "origin": (35.0036, 135.7785),
                    "dest": (35.0035, 135.7754),
                    "travelmode": "walking",
                },
            },
            {
                "time": "16:00", "end": "16:30",
                "name": "花見小路通",
                "type": "古蹟文化",
                "icon": "🌸",
                "coord": (35.0035, 135.7754),
                "desc": "漫步花見小路，欣賞茶屋與料亭林立的祇園傳統街景。",
                "tips": "嚴禁拍攝藝妓；禁止在街道上大聲喧嘩或飲食。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 11 分鐘",
                    "detail": "步行至鴨川",
                    "origin": (35.0035, 135.7754),
                    "dest": (35.0046, 135.7707),
                    "travelmode": "walking",
                },
            },
            {
                "time": "16:41", "end": "16:51",
                "name": "鴨川納涼床",
                "type": "體驗",
                "icon": "🌊",
                "coord": (35.0046, 135.7707),
                "desc": "在鴨川河畔的納涼床區感受京都初夏特有的水岸文化。",
                "tips": "納涼床用餐通常需提前預訂；未訂位可在河岸步道欣賞。",
                "green": "步行至鴨川，感受人與城市河川共存的生活方式。",
                "mood": "鴨川在黃昏的時候有種說不清楚的輕盈。涼床的燈一盞一盞亮起來，人聲和水聲混在一起，沒有哪個比哪個更大聲。這是京都少數讓你覺得城市本來應該是這樣的地方。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "步行至 iroha 北店",
                    "origin": (35.0046, 135.7707),
                    "dest": (35.0050, 135.7685),
                    "travelmode": "walking",
                },
            },
            {
                "time": "16:55", "end": "17:55",
                "name": "iroha 北店",
                "type": "散步購物",
                "icon": "🛍️",
                "coord": (35.0050, 135.7685),
                "desc": "在 iroha 北店挖掘日本古著、雜貨或特色商品。",
                "tips": "選擇二手或耐用品，減少一次性消費。",
                "green": "選購二手或耐用商品，實踐可持續消費。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 6 分鐘",
                    "detail": "步行至四条河原町",
                    "origin": (35.0050, 135.7685),
                    "dest": (35.0038, 135.7686),
                    "travelmode": "walking",
                },
            },
            {
                "time": "18:01", "end": "19:01",
                "name": "四条河原町",
                "type": "散步購物",
                "icon": "🏬",
                "coord": (35.0038, 135.7686),
                "desc": "逛高島屋、大丸、藥妝店；可補充旅途日用品與伴手禮。",
                "tips": "晚餐可在此覓食；旺季建議 19:30 前入座。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 6 分鐘",
                    "detail": "步行至新京極商店街",
                    "origin": (35.0038, 135.7686),
                    "dest": (35.0055, 135.7665),
                    "travelmode": "walking",
                },
            },
            {
                "time": "19:07", "end": "20:07",
                "name": "新京極商店街",
                "type": "散步購物",
                "icon": "🏮",
                "coord": (35.0055, 135.7665),
                "desc": "逛新京極商店街，購買八ツ橋、漬物、文具等京都特色伴手禮。",
                "tips": "晚餐可在商店街周邊尋覓；部分店舖 21:00 關門。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 5 分鐘",
                    "detail": "步行至寺町京極",
                    "origin": (35.0055, 135.7665),
                    "dest": (35.0060, 135.7657),
                    "travelmode": "walking",
                },
            },
            {
                "time": "20:12", "end": "21:12",
                "name": "寺町京極商店街",
                "type": "散步購物",
                "icon": "🏮",
                "coord": (35.0060, 135.7657),
                "desc": "逛寺町京極商店街，採購藥品、雜貨，感受大阪庶民購物文化。",
                "tips": "部分店舖 21:00 關門，注意時間。",
                "green": None,
                "transport_next": {
                    "mode": "京阪電車",
                    "walking": False,
                    "duration": "約 17 分鐘",
                    "detail": "祇園四条站（京阪）→ 五条站，步行 5 分至飯店",
                    "origin": (35.0060, 135.7657),
                    "dest": (34.9963, 135.7606),
                    "travelmode": "transit",
                },
            },
            {
                "time": "21:29", "end": "23:59",
                "name": "維瑟爾坎帕納京都五條飯店",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.9963, 135.7606),
                "desc": "返回飯店休息，整理採購物品，確認明日最後京都行程。",
                "tips": "明日下午移住大阪，行前確認大件行李整理。",
                "green": None,
                "transport_next": None,
            },
        ],
    },
    {
        "day": 3,
        "date": "2026/06/23（二）",
        "theme": "京都最後半日",
        "subtitle": "揮別古都，大阪初夜",
        "city": "京都 → 大阪心齋橋",
        "color": "#9B7EA6",
        "hotel": "心齋橋維亞酒店－JR 西日本集團",
        "mood": "離開一座城市的感覺，往往不是在車站，而是在某個普通的午後，當你意識到接下來的路線不再往飯店方向走——那一刻，「要離開了」才真正有了重量。",
        "stops": [
            {
                "time": "09:00", "end": "09:00",
                "name": "維瑟爾坎帕納京都五條飯店（退房）",
                "type": "住宿",
                "icon": "🧳",
                "coord": (34.9963, 135.7606),
                "desc": "退房並寄放行李，準備輕裝前往京都水族館。",
                "tips": "確認飯店是否可寄放行李至下午取回。",
                "green": None,
                "transport_next": {
                    "mode": "地下鐵烏丸線 + 步行",
                    "walking": False,
                    "duration": "約 60 分鐘",
                    "detail": "K10（五条）→ K11（京都），步行約 15 分鐘至梅小路公園",
                    "origin": (34.9963, 135.7606),
                    "dest": (34.9882, 135.7475),
                    "travelmode": "transit",
                },
            },
            {
                "time": "10:00", "end": "13:00",
                "name": "京都水族館",
                "type": "體驗",
                "icon": "🐠",
                "coord": (34.9882, 135.7475),
                "desc": "參觀京都水族館，欣賞海洋生物展示、水母區與企鵝館。",
                "tips": "館內有餐廳，可用午餐；或出館後在梅小路公園野餐。",
                "green": None,
                "transport_next": {
                    "mode": "京都市公車或步行",
                    "walking": False,
                    "duration": "約 22 分鐘",
                    "detail": "梅小路公園步行至四条烏丸附近，或搭公車至「四条烏丸」",
                    "origin": (34.9882, 135.7475),
                    "dest": (35.0050, 135.7649),
                    "travelmode": "transit",
                },
            },
            {
                "time": "13:22", "end": "14:52",
                "name": "錦市場",
                "type": "散步購物",
                "icon": "🥢",
                "coord": (35.0050, 135.7649),
                "desc": "漫步「京都的廚房」，品嘗漬物、豆腐、玉子燒、抹茶等在地小食。",
                "tips": "部分攤位有邊走邊吃的規定；人潮多時靠邊行走。",
                "green": "選購在地食材小食，支持傳統市場商家。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "錦市場步行即達",
                    "origin": (35.0050, 135.7649),
                    "dest": (35.0053, 135.7670),
                    "travelmode": "walking",
                },
            },
            {
                "time": "14:56", "end": "15:26",
                "name": "錦天滿宮",
                "type": "古蹟文化",
                "icon": "⛩️",
                "coord": (35.0053, 135.7670),
                "desc": "參拜錦市場的守護神社，感受商街信仰在地融合的京都日常。",
                "tips": "可購買御守；境內安靜參拜。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 25 分鐘",
                    "detail": "步行至祇園白川（建議沿鴨川散步至祇園）",
                    "origin": (35.0053, 135.7670),
                    "dest": (35.0055, 135.7745),
                    "travelmode": "walking",
                },
            },
            {
                "time": "15:51", "end": "16:51",
                "name": "祇園白川",
                "type": "散步購物",
                "icon": "🌊",
                "coord": (35.0055, 135.7745),
                "desc": "漫步祇園白川石板路，欣賞垂柳、小橋、茶屋並存的京都最美水岸。",
                "tips": "此區居民眾多，保持安靜；勿拍攝私人住家。",
                "green": None,
                "mood": "白川沿岸的垂柳在水面上拉出很長的倒影。這裡沒什麼大景點，沒有需要拍到的構圖——它就是那種讓人不想離開、但說不清楚原因的地方。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 9 分鐘",
                    "detail": "步行至挽肉と米",
                    "origin": (35.0055, 135.7745),
                    "dest": (35.003, 135.768),
                    "travelmode": "walking",
                },
            },
            {
                "time": "17:00", "end": "18:00",
                "name": "挽肉と米（京都）",
                "type": "晚餐",
                "icon": "🍚",
                "coord": (35.003, 135.768),
                "desc": "人氣名店，以絞肉漢堡排與白飯為主角，飯可無限添加。",
                "tips": "極人氣，強烈建議提早至現場取號；確認京都店位置。",
                "green": None,
                "transport_next": {
                    "mode": "JR 新快速 + Osaka Metro",
                    "walking": False,
                    "duration": "約 66 分鐘",
                    "detail": "回飯店取行李 → 京都站搭 JR 新快速至大阪站（約 30 分）→ Osaka Metro 御堂筋線至心齋橋站（約 10 分）→ 步行 5 分至飯店",
                    "origin": (35.003, 135.768),
                    "dest": (34.6735, 135.5010),
                    "travelmode": "transit",
                },
            },
            {
                "time": "19:06", "end": "19:36",
                "name": "心齋橋維亞酒店－JR 西日本集團",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.6735, 135.5010),
                "desc": "辦理大阪飯店入住，放置行李，整理後前往美國村散步。",
                "tips": "確認飯店早餐方案；心齋橋站步行約 3 分鐘。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "飯店步行至美國村",
                    "origin": (34.6735, 135.5010),
                    "dest": (34.6720, 135.4980),
                    "travelmode": "walking",
                },
            },
            {
                "time": "19:40", "end": "20:40",
                "name": "美國村（アメリカ村）",
                "type": "散步購物",
                "icon": "🎨",
                "coord": (34.6720, 135.4980),
                "desc": "逛大阪美國村，感受年輕文化、古著時尚與街頭藝術聚集地。",
                "tips": "夜間熱鬧，注意隨身物品；古著店探索有驚喜。",
                "green": "選擇二手古著，實踐可持續時尚。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "步行返回飯店",
                    "origin": (34.6720, 135.4980),
                    "dest": (34.6735, 135.5010),
                    "travelmode": "walking",
                },
            },
            {
                "time": "20:44", "end": "23:59",
                "name": "心齋橋維亞酒店－JR 西日本集團",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.6735, 135.5010),
                "desc": "返回飯店，確認明日 USJ 門票與交通路線。明日需早起。",
                "tips": "USJ 建議 07:00 前抵達，需提早起床。",
                "green": None,
                "transport_next": None,
            },
        ],
    },
    {
        "day": 4,
        "date": "2026/06/24（三）",
        "theme": "魔法樂園",
        "subtitle": "環球影城全日狂歡",
        "city": "大阪此花區（USJ）",
        "color": "#C9825A",
        "hotel": "心齋橋維亞酒店－JR 西日本集團",
        "mood": "有些地方的設計，就是要讓你忘記外面的世界。走進超級任天堂世界的那一刻，那種突然失去距離感的錯愕，本身就是整個體驗的一部分。",
        "stops": [
            {
                "time": "00:00", "end": "06:30",
                "name": "心齋橋維亞酒店（休息）",
                "type": "住宿",
                "icon": "😴",
                "coord": (34.6735, 135.5010),
                "desc": "充足睡眠，養精蓄銳準備全天 USJ 體驗。",
                "tips": "建議 06:00 起床準備出發。",
                "green": None,
                "transport_next": {
                    "mode": "Osaka Metro + JR 夢咲線",
                    "walking": False,
                    "duration": "約 30 分鐘",
                    "detail": "心齋橋站搭御堂筋線至梅田 → 轉 JR 環狀線至西九条 → 轉 JR 夢咲線至 Universal City",
                    "origin": (34.6735, 135.5010),
                    "dest": (34.6654, 135.4323),
                    "travelmode": "transit",
                },
            },
            {
                "time": "07:00", "end": "21:00",
                "name": "日本環球影城（USJ）",
                "type": "體驗",
                "icon": "🎢",
                "coord": (34.6654, 135.4323),
                "desc": "全天暢玩 USJ！重點：超級任天堂世界（需整理券）、哈利波特魔法世界、小小兵天地。",
                "tips": "07:00 入場後立刻至超級任天堂世界抽免費整理券；Express Pass 建議事先購買。",
                "green": "自備水瓶，減少園區一次性杯具使用；食物包裝集中丟棄。",
                "transport_next": {
                    "mode": "JR 夢咲線 + Osaka Metro",
                    "walking": False,
                    "duration": "約 26 分鐘",
                    "detail": "Universal City 搭 JR 夢咲線至西九条，轉大阪環狀線或 Osaka Metro 至心齋橋",
                    "origin": (34.6654, 135.4323),
                    "dest": (34.6720, 135.4985),
                    "travelmode": "transit",
                },
            },
            {
                "time": "21:26", "end": "22:26",
                "name": "海鮮屋台おくまん アメ村店",
                "type": "晚餐",
                "icon": "🦞",
                "coord": (34.6720, 135.4985),
                "desc": "居酒屋風格海鮮料理，犒賞全天 USJ 的疲勞。推薦海鮮串燒、炸物配大阪生啤。",
                "tips": "居酒屋多為現金；深夜可能需等候。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 2 分鐘",
                    "detail": "步行返回飯店",
                    "origin": (34.6720, 135.4985),
                    "dest": (34.6735, 135.5010),
                    "travelmode": "walking",
                },
            },
            {
                "time": "22:28", "end": "23:59",
                "name": "心齋橋維亞酒店－JR 西日本集團",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.6735, 135.5010),
                "desc": "返回飯店盥洗休息。USJ 後體力消耗大，直接休息。",
                "tips": "明日行程較輕鬆，可稍晚起床。",
                "green": None,
                "transport_next": None,
            },
        ],
    },
    {
        "day": 5,
        "date": "2026/06/25（四）",
        "theme": "難波掃貨",
        "subtitle": "大阪食都的全日採買",
        "city": "大阪難波 × 心齋橋",
        "color": "#C9A832",
        "hotel": "心齋橋維亞酒店－JR 西日本集團",
        "mood": "難波的熱鬧不假裝優雅。道頓堀的招牌大到有點衝擊，章魚燒的香氣直接飄進鼻腔，人群把馬路擠到像捷運車廂。大阪就是這樣，毫不保留。",
        "stops": [
            {
                "time": "07:00", "end": "08:00",
                "name": "心齋橋維亞酒店",
                "type": "早餐",
                "icon": "☕",
                "coord": (34.6735, 135.5010),
                "desc": "梳洗，在周邊便利商店或咖啡店享用早餐，準備木津市場行。",
                "tips": "今日行程集中難波，步行為主。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 15 分鐘",
                    "detail": "飯店步行至木津市場（約 1.2 km）",
                    "origin": (34.6735, 135.5010),
                    "dest": (34.6580, 135.5010),
                    "travelmode": "walking",
                },
            },
            {
                "time": "08:00", "end": "09:00",
                "name": "難波大阪木津市場",
                "type": "體驗",
                "icon": "🐟",
                "coord": (34.6580, 135.5010),
                "desc": "參觀大阪傳統生鮮批發市場，感受大阪飲食文化根源與在地食材生態。",
                "tips": "早晨人潮最多；部分攤位接受一般消費者購買漬物、熟食。",
                "green": "支持傳統市場，購買在地食材。",
                "mood": "市場的早晨有種別的地方沒有的腳步聲——不是觀光客的拖行，是熟練的、帶著目的的走路聲。在這裡，食物還沒有被美化，還帶著它本來的樣子。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 17 分鐘",
                    "detail": "步行至難波八阪神社",
                    "origin": (34.6580, 135.5010),
                    "dest": (34.6620, 135.4960),
                    "travelmode": "walking",
                },
            },
            {
                "time": "09:17", "end": "10:17",
                "name": "難波八阪神社",
                "type": "古蹟文化",
                "icon": "🦁",
                "coord": (34.6620, 135.4960),
                "desc": "參拜難波八阪神社，欣賞著名的獅子口大舞台建築。",
                "tips": "獅子殿是難得一見的建築特色；境內保持安靜。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 21 分鐘",
                    "detail": "步行至道頓堀",
                    "origin": (34.6620, 135.4960),
                    "dest": (34.6687, 135.5013),
                    "travelmode": "walking",
                },
            },
            {
                "time": "10:38", "end": "11:08",
                "name": "道頓堀",
                "type": "散步購物",
                "icon": "🎭",
                "coord": (34.6687, 135.5013),
                "desc": "漫步道頓堀，欣賞霓虹招牌、戎橋與大阪街頭美食。嘗試章魚燒或大阪燒。",
                "tips": "早上人潮相對少；戎橋可拍攝招牌全景。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 5 分鐘",
                    "detail": "步行至難波Walk地下街",
                    "origin": (34.6687, 135.5013),
                    "dest": (34.6660, 135.5010),
                    "travelmode": "walking",
                },
            },
            {
                "time": "11:13", "end": "12:13",
                "name": "難波Walk（地下街）",
                "type": "散步購物",
                "icon": "🛒",
                "coord": (34.6660, 135.5010),
                "desc": "逛難波地下購物街，採購時尚、雜貨、甜點等商品。",
                "tips": "難波Walk 連接多個車站，注意出口方向。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "步行至餐廳",
                    "origin": (34.6660, 135.5010),
                    "dest": (34.665, 135.501),
                    "travelmode": "walking",
                },
            },
            {
                "time": "12:17", "end": "13:17",
                "name": "新宿焼肉 牛たんの檸檬 大阪本店",
                "type": "午餐",
                "icon": "🥩",
                "coord": (34.665, 135.501),
                "desc": "大阪人氣牛舌燒肉午餐。推薦厚切牛舌定食，搭配麥飯與湯品。",
                "tips": "人氣高，可能需等候；確認 2026 年店舖位置。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "步行至 Bic Camera",
                    "origin": (34.665, 135.501),
                    "dest": (34.6638, 135.5018),
                    "travelmode": "walking",
                },
            },
            {
                "time": "13:21", "end": "14:21",
                "name": "Bic Camera 難波店",
                "type": "散步購物",
                "icon": "📷",
                "coord": (34.6638, 135.5018),
                "desc": "採購相機、家電、電子產品、美妝品。外國旅客可辦免稅（購滿 ¥5000）。",
                "tips": "需護照辦理免稅；確認商品電壓與規格可帶回台灣。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "步行至難波丸井",
                    "origin": (34.6638, 135.5018),
                    "dest": (34.6650, 135.5020),
                    "travelmode": "walking",
                },
            },
            {
                "time": "14:25", "end": "15:25",
                "name": "難波丸井（MARUI）",
                "type": "散步購物",
                "icon": "🏬",
                "coord": (34.6650, 135.5020),
                "desc": "採購日本時尚服飾、雜貨與美妝。多層不同品牌。",
                "tips": "部分樓層有外國旅客免稅優惠。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 6 分鐘",
                    "detail": "步行至難波CITY",
                    "origin": (34.6650, 135.5020),
                    "dest": (34.6620, 135.5005),
                    "travelmode": "walking",
                },
            },
            {
                "time": "15:31", "end": "16:31",
                "name": "難波CITY 本館",
                "type": "散步購物",
                "icon": "🏬",
                "coord": (34.6620, 135.5005),
                "desc": "逛難波CITY，採購時尚餐飲與日本特色商品。連接 JR 難波站。",
                "tips": "地下美食街可補充下午點心。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 5 分鐘",
                    "detail": "步行至難波公園",
                    "origin": (34.6620, 135.5005),
                    "dest": (34.6608, 135.5012),
                    "travelmode": "walking",
                },
            },
            {
                "time": "16:36", "end": "17:36",
                "name": "難波公園（Namba Parks）",
                "type": "散步購物",
                "icon": "🌿",
                "coord": (34.6608, 135.5012),
                "desc": "大阪都市綠化購物公園，屋頂花園可俯瞰城市；採購日本生活雜貨。",
                "tips": "屋頂花園落日前景觀美麗。",
                "green": "屋頂綠化設計是都市永續建築典範，感受綠意與商業空間共存。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 24 分鐘",
                    "detail": "步行至玄品心齋橋店",
                    "origin": (34.6608, 135.5012),
                    "dest": (34.6720, 135.5010),
                    "travelmode": "walking",
                },
            },
            {
                "time": "18:00", "end": "19:00",
                "name": "螃蟹河豚料理 玄品 心齋橋店",
                "type": "晚餐",
                "icon": "🦀",
                "coord": (34.6720, 135.5010),
                "desc": "大阪名物螃蟹與河豚料理，高級海鮮套餐體驗。",
                "tips": "強烈建議事先預約；確認 2026 年菜單與價格。",
                "green": "選擇嚴格管理食材的高品質海鮮餐廳，支持負責任漁業。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 5 分鐘",
                    "detail": "步行至心齋橋筋商店街",
                    "origin": (34.6720, 135.5010),
                    "dest": (34.6730, 135.5012),
                    "travelmode": "walking",
                },
            },
            {
                "time": "19:05", "end": "20:05",
                "name": "心齋橋筋商店街",
                "type": "散步購物",
                "icon": "🏮",
                "coord": (34.6730, 135.5012),
                "desc": "大阪著名有蓋拱廊商店街，採購藥妝、時尚品牌與大阪伴手禮。",
                "tips": "松本清、Sundrug 藥妝；UNIQLO、GU 品牌。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 4 分鐘",
                    "detail": "步行至道頓堀",
                    "origin": (34.6730, 135.5012),
                    "dest": (34.6687, 135.5013),
                    "travelmode": "walking",
                },
            },
            {
                "time": "20:09", "end": "21:09",
                "name": "道頓堀（夜間）",
                "type": "散步購物",
                "icon": "🌃",
                "coord": (34.6687, 135.5013),
                "desc": "夜間再訪道頓堀，感受霓虹燈光與大阪夜間最熱鬧的面貌。",
                "tips": "注意戎橋擁擠；保管好隨身物品。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 13 分鐘",
                    "detail": "步行返回飯店",
                    "origin": (34.6687, 135.5013),
                    "dest": (34.6735, 135.5010),
                    "travelmode": "walking",
                },
            },
            {
                "time": "21:22", "end": "23:59",
                "name": "心齋橋維亞酒店－JR 西日本集團",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.6735, 135.5010),
                "desc": "返回飯店休息，整理採購物品，確認明日梅田行程。",
                "tips": "整理今日採購，確認行李重量。",
                "green": None,
                "transport_next": None,
            },
        ],
    },
    {
        "day": 6,
        "date": "2026/06/26（五）",
        "theme": "梅田制霸",
        "subtitle": "天空庭園與日本最長商店街",
        "city": "大阪梅田 × 天神橋筋",
        "color": "#5A7AA6",
        "hotel": "心齋橋維亞酒店－JR 西日本集團",
        "mood": "梅田很大，大到讓人迷路不只是可能發生的事，是幾乎必然的儀式。但迷路了也沒關係——每次拐錯彎，都會遇到另一間沒有計劃中的店。",
        "stops": [
            {
                "time": "08:00", "end": "09:00",
                "name": "心齋橋維亞酒店",
                "type": "早餐",
                "icon": "☕",
                "coord": (34.6735, 135.5010),
                "desc": "享用早餐，準備前往梅田大型購物區。",
                "tips": "今日行程集中梅田，御堂筋線可快速往返。",
                "green": None,
                "transport_next": {
                    "mode": "Osaka Metro 御堂筋線",
                    "walking": False,
                    "duration": "約 30 分鐘",
                    "detail": "心齋橋站搭御堂筋線往梅田 → 步行 5 分至友都八喜",
                    "origin": (34.6735, 135.5010),
                    "dest": (34.7048, 135.4965),
                    "travelmode": "transit",
                },
            },
            {
                "time": "09:30", "end": "11:00",
                "name": "友都八喜相機 梅田店",
                "type": "散步購物",
                "icon": "📷",
                "coord": (34.7048, 135.4965),
                "desc": "全日本最大友都八喜旗艦店，採購相機、家電、遊戲機、美妝保養品。",
                "tips": "外國旅客免稅（¥5000 起，需護照）；確認電壓規格。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 2 分鐘",
                    "detail": "相鄰建築步行即達",
                    "origin": (34.7048, 135.4965),
                    "dest": (34.7025, 135.4958),
                    "travelmode": "walking",
                },
            },
            {
                "time": "11:02", "end": "12:32",
                "name": "LUCUA Osaka",
                "type": "散步購物",
                "icon": "🏬",
                "coord": (34.7025, 135.4958),
                "desc": "逛 LUCUA 與 LUCUA 1100，採購時尚服飾、設計雜貨。連接 JR 大阪站。",
                "tips": "10F 餐廳樓層可在此用午餐；地下美食街選擇豐富。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 14 分鐘",
                    "detail": "步行至梅田空中庭園",
                    "origin": (34.7025, 135.4958),
                    "dest": (34.7053, 135.4897),
                    "travelmode": "walking",
                },
            },
            {
                "time": "12:46", "end": "13:46",
                "name": "梅田空中庭園（展望台）",
                "type": "體驗",
                "icon": "🌆",
                "coord": (34.7053, 135.4897),
                "desc": "登上梅田空中庭園展望台，360 度俯瞰大阪市景，晴天可遠眺六甲山。",
                "tips": "門票約 ¥1500+；豪華版關西樂享周遊券可能含此項目。",
                "green": None,
                "mood": "從展望台往下看，大阪展開成一張地圖，但比地圖更混亂也更真實。遠處的山脈和市區的煙囪並排出現在同一個視野裡，讓你意識到城市從來沒有真正結束，它只是慢慢變得安靜。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 8 分鐘",
                    "detail": "步行至 Grand Front Osaka",
                    "origin": (34.7053, 135.4897),
                    "dest": (34.7045, 135.4945),
                    "travelmode": "walking",
                },
            },
            {
                "time": "13:54", "end": "14:54",
                "name": "無印良品 Grand Front Osaka 店",
                "type": "散步購物",
                "icon": "⬜",
                "coord": (34.7045, 135.4945),
                "desc": "採購無印良品生活用品、食品、文具與旅行小物。",
                "tips": "Grand Front 亦有多間特色餐廳，可在此用午餐。",
                "green": "無印良品設計哲學強調簡單、耐用、減少過度包裝，是永續消費的選擇。",
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 22 分鐘",
                    "detail": "步行至 HEP FIVE",
                    "origin": (34.7045, 135.4945),
                    "dest": (34.7045, 135.5005),
                    "travelmode": "walking",
                },
            },
            {
                "time": "15:16", "end": "17:16",
                "name": "HEP FIVE 購物中心",
                "type": "散步購物",
                "icon": "🎡",
                "coord": (34.7045, 135.5005),
                "desc": "逛 HEP FIVE，採購年輕時尚品牌；可搭乘屋頂著名的紅色摩天輪。",
                "tips": "摩天輪票約 ¥600；傍晚夕陽角度最美。",
                "green": None,
                "transport_next": {
                    "mode": "Osaka Metro 谷町線",
                    "walking": False,
                    "duration": "約 19 分鐘",
                    "detail": "梅田站搭谷町線至南森町站，步行 5 分至天神橋筋商店街",
                    "origin": (34.7045, 135.5005),
                    "dest": (34.7010, 135.5115),
                    "travelmode": "transit",
                },
            },
            {
                "time": "17:35", "end": "20:35",
                "name": "天神橋筋商店街（日本第一長拱廊）",
                "type": "散步購物",
                "icon": "🏮",
                "coord": (34.7010, 135.5115),
                "desc": "漫步日本最長商店街（全長約 2.6km），逛在地食品、庶民服飾、生活雜貨。",
                "tips": "從 1 丁目逛至 6 丁目；多間居酒屋與食堂可用晚餐。",
                "green": "優先選擇在地小店，感受大阪庶民真實生活尺度。",
                "mood": "天神橋筋不是為觀光客設計的商店街。魚店老闆在招呼鄰居，修鞋店的燈還亮著，水果攤的價格用手寫牌子標。走在這裡，你是訪客，但不會感覺被當作商品。",
                "transport_next": {
                    "mode": "Osaka Metro",
                    "walking": False,
                    "duration": "約 18 分鐘",
                    "detail": "南森町搭谷町線至天王寺，轉御堂筋線至心齋橋站，步行至飯店",
                    "origin": (34.7010, 135.5115),
                    "dest": (34.6735, 135.5010),
                    "travelmode": "transit",
                },
            },
            {
                "time": "20:53", "end": "23:59",
                "name": "心齋橋維亞酒店－JR 西日本集團",
                "type": "住宿",
                "icon": "🏨",
                "coord": (34.6735, 135.5010),
                "desc": "返回飯店整理採購，確認明日返台行程，預先打包行李。",
                "tips": "明日退房，確認去 KIX 的交通路線；回程行李建議事先秤重。",
                "green": None,
                "transport_next": None,
            },
        ],
    },
    {
        "day": 7,
        "date": "2026/06/27（六）",
        "theme": "歸途",
        "subtitle": "林口折扣與關西道別",
        "city": "大阪 → りんくう → KIX → 台灣",
        "color": "#8A8A8A",
        "hotel": "臺灣桃園國際機場",
        "mood": "離開一個地方，往往不是在起飛的那一刻，而是在最後一次把行李箱拉桿推上去的聲音裡。行程結束了，但你帶走的，有些比你以為的更重。",
        "stops": [
            {
                "time": "08:00", "end": "09:00",
                "name": "心齋橋維亞酒店（早餐 × 退房）",
                "type": "早餐",
                "icon": "🧳",
                "coord": (34.6735, 135.5010),
                "desc": "最後一個大阪早晨，享用早餐後退房，寄放行李，輕裝在周邊自由活動。",
                "tips": "退房前確認行李重量，避免機場超重。",
                "green": None,
                "transport_next": {
                    "mode": "步行",
                    "walking": True,
                    "duration": "約 10 分鐘",
                    "detail": "飯店步行至美國村 Red Rock",
                    "origin": (34.6735, 135.5010),
                    "dest": (34.6720, 135.4982),
                    "travelmode": "walking",
                },
            },
            {
                "time": "12:00", "end": "13:00",
                "name": "Red Rock Amemura",
                "type": "午餐",
                "icon": "🥩",
                "coord": (34.6720, 135.4982),
                "desc": "美村的人氣名店，以和牛ローストビーフ丼（烤牛肉蓋飯）聞名，CP 值高。",
                "tips": "排隊人潮多，建議 11:30 前到場取號；確認 2026 年營業時間。",
                "green": None,
                "transport_next": {
                    "mode": "Osaka Metro + 南海電鐵/JR",
                    "walking": False,
                    "duration": "約 40 分鐘",
                    "detail": "回飯店取行李 → 心齋橋→難波→南海電鐵至泉佐野或 JR 至りんくうタウン站，步行 5 分至アウトレット",
                    "origin": (34.6720, 135.4982),
                    "dest": (34.4115, 135.2960),
                    "travelmode": "transit",
                },
            },
            {
                "time": "13:40", "end": "14:40",
                "name": "りんくうプレミアム・アウトレット",
                "type": "散步購物",
                "icon": "🛍️",
                "coord": (34.4115, 135.2960),
                "desc": "機場旁高級折扣購物村，採購 COACH、KATE SPADE 及日本品牌折扣商品。",
                "tips": "距 KIX 約 10 分鐘車程，購物後直接前往機場；確認可托運或手提。",
                "green": "選購耐用精品，以質量取代數量，減少一次性消費。",
                "transport_next": {
                    "mode": "JR 關西空港線或南海電鐵",
                    "walking": False,
                    "duration": "約 20 分鐘",
                    "detail": "りんくうタウン站搭 JR 關西空港線或南海電鐵至関西空港站（約 7 分）",
                    "origin": (34.4115, 135.2960),
                    "dest": (34.4320, 135.2304),
                    "travelmode": "transit",
                },
            },
            {
                "time": "16:00", "end": "20:00",
                "name": "關西國際機場（出境）",
                "type": "出發",
                "icon": "✈️",
                "coord": (34.4320, 135.2304),
                "desc": "辦理 check-in、托運行李、安全檢查，在免稅區購物與候機。航班 20:00 起飛。",
                "tips": "推薦機場免稅店：酒類、零食、化妝品；確認登機門位置。",
                "green": None,
                "transport_next": None,
            },
            {
                "time": "20:00", "end": "21:50",
                "name": "飛行中 KIX → TPE",
                "type": "交通",
                "icon": "🛫",
                "coord": (30.0, 128.0),
                "desc": "飛行時間約 2 小時 50 分，抵達台灣時間 21:50（台灣時間）。",
                "tips": "在機上整理旅程紀錄，思考帶回家的不只是行李。",
                "green": None,
                "transport_next": None,
            },
            {
                "time": "21:50", "end": "23:59",
                "name": "臺灣桃園國際機場",
                "type": "抵達",
                "icon": "🏠",
                "coord": (25.0777, 121.2328),
                "desc": "回到台灣，辦理入境、領取行李，搭桃園捷運或客運返家。",
                "tips": "入境申報不符規定食品、藥品等需在海關申報。",
                "green": None,
                "transport_next": None,
            },
        ],
    },
]
